repos:
- hooks:
  - exclude: (docs|\.phan)
    id: trailing-whitespace
  - id: end-of-file-fixer
  - exclude: (.vscode)
    id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
